#!/bin/ksh
# *****************************COPYRIGHT******************************
# (C) Crown copyright Met Office. All rights reserved.
# For further details please refer to the file COPYRIGHT.txt
# which you should have received as part of this distribution.
# *****************************COPYRIGHT******************************
#
#  Script: bcreconf
#
#  Purpose:  Utility to reconfigure Boundary datasets.
#
#  Current Owner: W Roseblade    Date: 1/02/06
#  Reviewer: M Saunby            Date: 1/02/06
#
#  Tested under OS version: UNICOS version 6
#  UM   version no: 4.4  Date of test:  27/8/97
#
#  History:
#   Model
#  version  Date         Modification history:
#  4.4      2/6/97       Original version Ian Edmond
#  4.5      01/10/98     Initialise UM_SECTOR_SIZE. D. Robinson.
#  4.5      01/09/98     Removed UMVERSION. K Rogers
#  4.5c     02/03/98     Changed version from 4.5 to 4.5c. W Roseblade
#  5.0      02/03/99     Changed version from 4.5 to 5.0. W Roseblade
#  5.1      04/05/00     Added TARGET_MC to cater for different build
#                        configurations (R.Hatcher)
#  5.1      14/03/00     Changed version from 5.0 to 5.1. W Roseblade
#  5.2      30/08/00     New Header Format W.Roseblade
#  5.2      27/10/00     Set TARGET_MC using @target_mc@ tag (R.Hatcher)
#  5.3    12/12/01     Cater for exported value of EXEC (M.Hughes)
#  6.0      01/12/03     Change TMPDIR to point to $SCRATCH for NEC
#                        W Roseblade.
#  6.1      15/09/04     Introduce exchange of @vn@ tag for $VN
#                        in util scripts.               P.Dando
#  6.1      23/09/04     Replace exit 0 with exit $CC.
#                        W Roseblade.
#  6.2      25/08/06     Remove space between #! /bin/ksh W Roseblade.
#
#  Programming standard: UMDP 3, version 7.2
#
#  External documentation: none
#
#
#  Interface and arguments:
#
#  bcreconf  -n namelist [-v vertical_namelist] \
#                         input_boundary_dataset output_boundary_dataset
#
#   3 or more arguments as follows:
#        $1 -n <namelist>                   : Namelists (see below)
#                                           :
#        $2 (optional) -v vertical_namelist : Only needed if
#                                           : LVERTINT =T or
#                                           : LLEVDEPC =T  (see below)
#        $3  input_boundary_dataset         : Input boundary dataset
#                                           :
#        $4  output_boundary_dataset        : Output boundary dataset
#                                           :
#
#   -------------------------------------------------------------------
#   Called by : none
#   Calls     :  bcreconf
#
#   Imports:
#     VN - Version number of the program library to be used.
#     TARGET_MC - Name for the build configuration directory (also the
#                 name of the platform on which the model exec is run).
#     TMPDIR - Directory in which output redirected to.
#
#   Exports
#     UM_SECTOR_SIZE - UM Sector Size ie 2048
#     UNIT22         - $UMDIR/vn$VN/ctldata/STASHmaster
#
#   Local variables:
#     BCIN              - Input boundary dataset name
#     BCOUT             - Output boundary dataset name
#     EXEC              - Directory containing executable
#                         ie $UMDIR/vn$VN/exec
#     namelist_set      - flag set to true if namelists supplied
#     vert_namelist_set - flag set to true if vertical namelists
#                         supplied
#     inputbf           - flag set to true if input boundary file
#                         supplied
#     namelists         - supplied namelist(s)
#     vert_namelist     - supplied vertical namelist(s)
#     option            - varable holding y or n response to
#                         overwrite file
#
#
# End of header -------------------------------------------------------

if [ $# -lt 3 ]
  then
    echo "Usage: bcreconf  -n namelist [-v vertical_namelist] \
input_boundary_dataset output_boundary_dataset "

    exit 1
fi

# Step 0 - Set up environment variables
#

# VN here is automatically set in this script at each UM build
VN=@vn@

# Directory for intermediate files
TMPDIR=$SCRATCH

# Build configuration directory
TARGET_MC=@target_mc@

# Directory containing executable
EXEC=${EXEC:-$UMDIR/vn$VN/$TARGET_MC/exec}

# UM Sector Size
UM_SECTOR_SIZE=${UM_SECTOR_SIZE:-2048}
export UM_SECTOR_SIZE

export UNIT22=$UMDIR/vn$VN/ctldata/STASHmaster

assign -f 77 g:sf

# Step 1 -  Read filenames specified in argument list and check syntax.
#
namelist_set=false
vert_namelist_set=false
inputbf=false

while [ $# -gt 0 ]               # Loop over all command line arguments

do
 case "$1" in

 -n)
    if [ ! -f  $2 ]            # Check input files exist.
    then

      echo "namelist $2 does not exist"
      exit 1

    fi

    namelists=$2
    namelist_set=true
    shift
    ;;
 -v)
    if [ ! -f  $2 ]            # Check input files exist.
    then

      echo "vertical namelist file $2 does not exist"
      exit 1

    fi

    vert_namelist=$2
    vert_namelist_set=true
    shift
    ;;
 *)
    if [ $namelist_set = true ]
      then

        if [ $# -eq 2 ]
          then

            if [ ! -f  $1 ]            # Check input files exist.
              then

                echo "boundary file $1 does not exist"
                exit 1

            fi
            export BCIN=$1
            inputbf=true

        elif [ $# -eq 1 ]
          then
            if [ $inputbf = false ]
              then

            echo "Usage: bcreconf  -n namelist [-v vertical_namelist] \
input_boundary_dataset output_boundary_dataset "
                exit 1

            fi
            if [ ! -f  $1 ]
              then

                export BCOUT=$1
            else

                echo "WARNING: file $1 already exists"
                echo "Do you want to overwrite this file (y or n)?"
                read option

                case "$option" in

                y)
                  export BCOUT=$1
                  ;;
                n)
                  exit 0
                  ;;
                *)
                  echo "Invalid answer"
                  exit 1
                  ;;
                esac

            fi
        else
          echo "Usage: bcreconf  -n namelist [-v vertical_namelist] \
input_boundary_dataset output_boundary_dataset "
          exit 1
        fi


    else
          echo "Usage: bcreconf  -n namelist [-v vertical_namelist] \
input_boundary_dataset output_boundary_dataset "
       exit 1
    fi
    ;;
    esac
    shift
    done

# Step 2 - Append vertical namelists files onto standard namelist
if [ $namelist_set = true -a $vert_namelist_set = true ]
  then

     cat $namelists $vert_namelist > $TMPDIR/bc_namelists.$$

elif [ $namelist_set = true -a $vert_namelist_set = false ]
  then

     cat $namelists > $TMPDIR/bc_namelists.$$

fi


# Step 2 - Execute utility & print out messages.
#
$EXEC/bcreconf < $TMPDIR/bc_namelists.$$ 1> $TMPDIR/bcreconf_out.$$ 2>&1

CC=$?
if [ $CC != 0 ]
then
echo 'Problem with BC Reconfiguration program'
fi

cat $TMPDIR/bcreconf_out.$$
echo 'BCRECONF output in:' $TMPDIR/bcreconf_out.$$

# Step 3 - Delete temporary files and exit
#
rm $TMPDIR/bc_namelists.$$
exit $CC
