! CLCFPT3A defines pointers in CLOUD_OVERLAP for two-stream radiation
! code.
!
! note that several pointers are identical since only certain
! groups of coefficients are relevant to a particular scheme.

      INTEGER,PARAMETER:: IP_CLOVLP_GFF=1 ! GAMMA-FREE-FREE
      INTEGER,PARAMETER:: IP_CLOVLP_GFC=2 ! GAMMA-FREE-CLOUD
      INTEGER,PARAMETER:: IP_CLOVLP_GCF=3 ! GAMMA-CLOUD-FREE
      INTEGER,PARAMETER:: IP_CLOVLP_GCC=4 ! GAMMA-CLOUD-CLOUD
      INTEGER,PARAMETER:: IP_CLOVLP_BFF=5 ! BETA-FREE-FREE
      INTEGER,PARAMETER:: IP_CLOVLP_BFC=6 ! BETA-FREE-CLOUD
      INTEGER,PARAMETER:: IP_CLOVLP_BCF=7 ! BETA-CLOUD-FREE
      INTEGER,PARAMETER:: IP_CLOVLP_BCC=8 ! BETA-CLOUD-CLOUD
      INTEGER,PARAMETER:: IP_CLOVLP_GFM=5 ! GAMMA_F-
      INTEGER,PARAMETER:: IP_CLOVLP_GFP=6 ! GAMMA_F+
      INTEGER,PARAMETER:: IP_CLOVLP_BFM=7 ! BETA_F-
      INTEGER,PARAMETER:: IP_CLOVLP_BFP=8 ! BETA_F+
      INTEGER,PARAMETER:: IP_CLOVLP_GM=5  ! GAMMA_-
      INTEGER,PARAMETER:: IP_CLOVLP_GP=6  ! GAMMA_+
      INTEGER,PARAMETER:: IP_CLOVLP_BM=7  ! BETA_-
      INTEGER,PARAMETER:: IP_CLOVLP_BP=8  ! BETA_+

      ! pointers for triple overlaps:

      INTEGER,PARAMETER:: IP_CLOVLP_V11=1
      INTEGER,PARAMETER:: IP_CLOVLP_V12=2
      INTEGER,PARAMETER:: IP_CLOVLP_V13=3
      INTEGER,PARAMETER:: IP_CLOVLP_V21=4
      INTEGER,PARAMETER:: IP_CLOVLP_V22=5
      INTEGER,PARAMETER:: IP_CLOVLP_V23=6
      INTEGER,PARAMETER:: IP_CLOVLP_V31=7
      INTEGER,PARAMETER:: IP_CLOVLP_V32=8
      INTEGER,PARAMETER:: IP_CLOVLP_V33=9
      INTEGER,PARAMETER:: IP_CLOVLP_U11=10
      INTEGER,PARAMETER:: IP_CLOVLP_U12=11
      INTEGER,PARAMETER:: IP_CLOVLP_U13=12
      INTEGER,PARAMETER:: IP_CLOVLP_U21=13
      INTEGER,PARAMETER:: IP_CLOVLP_U22=14
      INTEGER,PARAMETER:: IP_CLOVLP_U23=15
      INTEGER,PARAMETER:: IP_CLOVLP_U31=16
      INTEGER,PARAMETER:: IP_CLOVLP_U32=17
      INTEGER,PARAMETER:: IP_CLOVLP_U33=18

! CLCFPT3A end
