#!/bin/ksh
# *****************************COPYRIGHT******************************
# (C) Crown copyright Met Office. All rights reserved.
# For further details please refer to the file COPYRIGHT.txt
# which you should have received as part of this distribution.
# *****************************COPYRIGHT******************************
#
#  Function:  initxport
#
#  Purpose: Initialises & exports filenames of input and output
#           dumps/fieldsfiles.
#
#  Current Owner: W Roseblade    Date: 1/02/06
#  Reviewer: M Saunby            Date: 1/02/06
#
#  Tested under OS version: UNICOS 2.0.060f
#  UM version no: 4.5       Date of test:  <date of test>
#
#  History:
#   Model
#  version  Date        Modification history:
#   4.5     14/07/98    Original version (A Van der Wal).
#   5.2     14/09/00    New Header Format W Roseblade
#
#  Programming standard: UMDP 3, version unknown
#
#  External documentation:
#    <UMDP number & name of external documentation>
#
#   Interface and arguments: none
#
#   -------------------------------------------------------------------
#
#   Called by: fieldop
#   Calls    : none
#
#   Imports  :
#     TMPDIR
#
#   Exports  : none
#
#   Local variables:
#     tmpfile
#     files
#     i
#     FILE
#
#
#   End of header -----------------------------------------------------

initxport()
{
# Temporary file in which commands to initialise and export FILE1
# FILE2 (and FILE3) are written.
tmpfile=$TMPDIR/tmp$$
rm $tmpfile 2> /dev/null

files=$#
i=0

while [ $# -gt 0 ]
do

 i=`expr $i + 1`
# Insert commands for initialising and exporting input and output
# filenames into temporary file.
 FILE=$1
 echo "FILE$i=$1" >> $tmpfile
 echo "export FILE$i" >> $tmpfile

 if [ ! -f  $FILE ]            # Check input files exist.
 then

   if [ $i -ne $files ]
   then

     echo "$FILE does not exist"
     exit 1

   fi
 fi
 shift

done

# Execute temporary file/script.
chmod +x $tmpfile
. $tmpfile

}
