!
!  Tabulation of photolysis rates
!
!  3/1/2006 Modified to add CO2 photolysis. Olaf Morgenstern
!  9/3/2006 Mofified to include O2 branching O. Morgenstern

      REAL TABJ2A   (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJ2B   (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJ3    (JPLEV,JPCHI,JPTEM,JPO3P)  
      REAL TABJ3A   (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJNO   (JPLEV,JPCHI,JPTEM,JPO3P)  
      REAL TABJNO31 (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJNO32 (JPLEV,JPCHI,JPTEM,JPO3P)  
      REAL TABJNO2  (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJN2O5 (JPLEV,JPCHI,JPTEM,JPO3P)  
      REAL TABJHNO3 (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJH2O  (JPLEV,JPCHI,JPTEM,JPO3P)  
      REAL TABJH2O2 (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJF11  (JPLEV,JPCHI,JPTEM,JPO3P)  
      REAL TABJF12  (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJF22  (JPLEV,JPCHI,JPTEM,JPO3P)  
      REAL TABJF113 (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJCH3CL(JPLEV,JPCHI,JPTEM,JPO3P)  
      REAL TABJCCL4 (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJCNITA(JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJCNITB(JPLEV,JPCHI,JPTEM,JPO3P)  
      REAL TABJHCL  (JPLEV,JPCHI,JPTEM,JPO3P) 
      REAL TABJHOCL (JPLEV,JPCHI,JPTEM,JPO3P)  
      REAL TABJPNA  (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJCL2O2(JPLEV,JPCHI,JPTEM,JPO3P)  
      REAL TABJN2O  (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJBRCL (JPLEV,JPCHI,JPTEM,JPO3P)  
      REAL TABJBRNO3(JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJHOBR (JPLEV,JPCHI,JPTEM,JPO3P)  
      REAL TABJBRO  (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJOCLO (JPLEV,JPCHI,JPTEM,JPO3P) 
      REAL TABJC2OA (JPLEV,JPCHI,JPTEM,JPO3P)
      REAL TABJC2OB (JPLEV,JPCHI,JPTEM,JPO3P) 
      REAL TABJMHP  (JPLEV,JPCHI,JPTEM,JPO3P) 
      REAL TABJMCFM (JPLEV,JPCHI,JPTEM,JPO3P) 
      REAL TABJCH3BR(JPLEV,JPCHI,JPTEM,JPO3P) 
      REAL TABJF12B1(JPLEV,JPCHI,JPTEM,JPO3P) 
      REAL TABJF13B1(JPLEV,JPCHI,JPTEM,JPO3P) 
      REAL TABJCOF2 (JPLEV,JPCHI,JPTEM,JPO3P) 
      REAL TABJCOFCL(JPLEV,JPCHI,JPTEM,JPO3P) 
      REAL TABJCH4  (JPLEV,JPCHI,JPTEM,JPO3P) 
      REAL TABJCOS  (JPLEV,JPCHI,JPTEM,JPO3P) 
      REAL TABJSO2  (JPLEV,JPCHI,JPTEM,JPO3P)      
      REAL TABJCO2  (JPLEV,JPCHI,JPTEM,JPO3P) 

      REAL TABPRES(JPLEV),TABANG(JPCHI),TABT(JPTEM),TABO3(JPO3P)

      COMMON/TABB/                                                      &   
        TABJ2A,TABJ2B,TABJ3,TABJ3A   ,TABJNO   ,TABJNO31 ,              &   
        TABJNO32 ,TABJNO2  ,TABJN2O5 ,TABJHNO3 ,TABJH2O  ,              &     
        TABJH2O2 ,TABJF11  ,TABJF12  ,TABJF22  ,TABJF113 ,              &     
        TABJCH3CL,TABJCCL4 ,TABJCNITA,TABJCNITB,TABJHCL,TABJHOCL,       &    
        TABJPNA  ,TABJCL2O2,TABJN2O  ,TABJBRCL ,TABJBRNO3,              &    
        TABJHOBR ,TABJBRO  ,TABJOCLO ,TABJC2OA ,TABJC2OB ,              & 
        TABJMHP  ,TABJMCFM ,TABJCH3BR,TABJF12B1,TABJF13B1,              &
        TABJCOF2 ,TABJCOFCL,TABJCH4  ,SAO3C,                            & 
        TABPRES  ,TABANG   ,TABT     ,TABO3    ,TABJCOS  ,              &
        TABJSO2  ,TABJCO2                      
