!-----------------------------------------------------------------------
!L  COMDECK DOCACAG
!L  ---------------
!L    COMACDG CONTAINS PARAMETERS CONTROLLING DIAGNOSTIC PRINTOUT
!L
!L    LDIAGAC =.FALSE. SWITCHES OFF ALL DIAGNOSTICS
!L    LLDAC(#)=.FALSE. SWITCHES OFF DIAGNOSTICS OF TYPE #
!L
!L    DIAGNOSTIC TYPES & THEIR ASSOCIATED PARAMETERS ARE :-
!L    --------------------------------------------------
!L
!L    LLDAC(1) = .TRUE.
!L    -----------------
!L
!L    DETAILED DIAGNOSTICS ON A SHORT LIST OF OBSERVATIONS
!L    TO BE DONE FROM AC ETC.
!L    THIS TYPE OF DIAGNOSTIC IS SET-UP & USED BY TYPE 5 IF LLDAG0=T.
!L    AFTER EACH ITERATION THE LIST OF OBS INFLUENCING THE SELECTED PNT
!L    IS ADDED TO MDACO. THUS FOR SUBSEQUENT ITERATIONS DETAILED
!L    DIAGNOSTICS ON THESE OBS ARE OBTAINED. TO GET THIS MODE SET
!L    LLDAC(5)=T LLDAG0=T.
!L
!L    THIS TYPE CAN ALSO BE SWITCHED ON INDEPENDENTLY OF TYPE 5 BY :-
!L    MODACO  MODE FOR SETTING UP LIST MDAC:-
!L            1 TAKE FIRST NDACP OBS IN CURRENT VECTOR
!L            2 SEARCH FOR THOSE OBS IN MDACO DEFINED IN NAMELIST ADIAG
!L            3 SEARCH FOR THOSE OBS IN LTD AREA FROM    NAMELIST ADIAG
!L
!L    NDACOP  MAX NO OF OBS ON WHICH DIAGNOSTICS ARE REQUIRED
!L    NDACO       NO OF OBS ON WHICH DIAGNOSTICS ARE REQUIRED
!L    MDACO     LIST OF OBS ON WHICH DIAGNOSTICS ARE REQUIRED
!L              POINTS TO POSITION OF OB IN COMOBS.
!L
!L    NDACP  MAX NO OF OBS OF CURRENT TYPE ON WHICH DIAGS REQD.
!L    NDAC       NO OF OBS OF CURRENT TYPE ON WHICH DIAGS REQD.
!L    MDAC     LIST OF OBS OF CURRENT TYPE ON WHICH DIAGS REQD.
!L              POINTS TO POSITION OF OB IN CURRENT VECTORS FROM GETOBS.
!L
!L    NDACVP  MAX NO OF PARAMETERS WHICH CAN BE STORED FOR EACH OB
!L    NDACV       NO OF PARAMETERS WHICH ARE    STORED FOR EACH OB
!L    DACV        STORED PARAMETERS FOR EACH OB
!L    CACV        DESCRIPTION OF EACH PARAMETER
!L    CACT1/2/3/4 TITLES SET UP BY DACOIN
!L    LTITLE      CONTROLS TITLING OF OUTPUT FROM DACOUT
!L
!L    LLDAC(2) = .TRUE.
!L    -----------------
!L    STATISTICS OF OBSERVATION-MODEL INCREMENTS
!L    PRINTED OUT IN DIAGO
!L    MDIAGTPS: LIST OF TYPES TO BE PROCESSED BY DIAGO.
!L              SET MDIAGTPS(1)=0 FOR 'ALL'(DEFAULT).
!L    MDIAG:    1 = ONLY CALLS FROM AC PROCESSED
!L              2 = ONLY CALLS FROM Van### BEFORE VRTF PROCESSED
!L              4 = ONLY CALLS FROM Van### AFTER VRTF PROCESSED
!L                  (Van### is group of vertical analysis routines)
!L              0 = ALL CALLS PROCESSED (DEFAULT)
!L              BINARY COMBINATIONS SUPPORTED.
!L    LLBAND:   F = GLOBAL STATISTICS (DEFAULT).
!L              T = SEPARATE STATISTICS FOR BANDS 90N-22N,
!L                                                22N-22S,
!L                                                22S-90S.
!L    LRMS   :   T/F = Print RMS/Mean Square Values. Default = T.
!L    LNORMF :   T : Use Normalisation Factors (NF) as weights (Default)
!L           :   F : Set NF to 1.0 (ie. no weights used).
!L    LTEMP  :   T : Print Temperature statistics. Default. Theta
!L                   Increments are converted to temperature increments
!L                   and p* is assumed to be 1000mb for all obs.
!L           :   F : Print Theta statistics.
!L    LVERIF :   T : Sets parameters to get statistics for verification
!L                   purposes. LRMS=T,LTEMP=T,LNORMF=F,LGEO=F,LHYDR=F
!L           :   F : Default.
!L
!L    LLDAC(3) = .TRUE.
!L    -----------------
!L    STATISTICS OF INCREMENTS ON ANALYSIS GRID
!L
!L    LLDAC(4) = .TRUE.
!L    -----------------
!L    STATISTICS OF INCREMENTS ON MODEL GRID
!L    PRINTED OUT IN MMSPT
!L    MEAN AND MEAN-SQUARE OF INCREMENTS PRINTED FOR :-
!L        1. THE WHOLE MODEL(NOT WITH GEOSTROPHIC INCREMENTS)
!L    AND 2. EACH LEVEL OF THE MODEL
!L
!L    LLDAC(5) = .TRUE.
!L    -----------------
!L    DETAILS OF OBS INFLUENCING A SPECIFIED POINT.
!L    PARAMETERS IN NAMELIST ADIAG :-
!L    DAGLAT  -  LATITUDE  OF SPECIFIED POINT. DEFAULT =  57.0
!L    DAGLON  -  LONGITUDE OF SPECIFIED POINT. DEFAULT = 340.0
!L    LLDAG0      = SWITCH ON OPTION 1 FOR THOSE OBS FOUND, SO THAT
!L                   THEIR DETAILS ARE PRINTED NEXT TIME THROUGH AC.
!L    LLDAG(NAVT) = DO DIAGNOSTIC  FOR THIS VARIABLE TYPE.
!L
!-----------------------------------------------------------------------
