! SCLFND3A defines data for scaling functions in two-stream radiation
! code

      DATA N_SCALE_VARIABLE(IP_SCALE_POWER_LAW)/2/
      DATA N_SCALE_VARIABLE(IP_SCALE_FNC_NULL)/0/
      DATA N_SCALE_VARIABLE(IP_SCALE_POWER_QUAD)/3/
      DATA N_SCALE_VARIABLE(IP_SCALE_DOPPLER_QUAD)/4/
      DATA N_SCALE_VARIABLE(IP_SCALE_WENYI)/0/

! SCLFND3A end
