! OCTWKGEN
!
! History:
! Version  Date     Comment
! -------  ----     -------
!  6.1   02/09/04  Implement Pressure Correction scheme. M. Martin.

      REAL :: SSFUB(IMT_CLN)
      REAL :: SSFVB(IMT_CLN)
      REAL :: SSFUBP(IMT_CLN)
      REAL :: SSFVBP(IMT_CLN)
      REAL :: SSFUBPP(IMT_BIH)
      REAL :: SSFVBPP(IMT_BIH)
      REAL :: UCLIN(IMT,KM)
      REAL :: VCLIN(IMT,KM)
      REAL :: USAV(IMT,KM)
      REAL :: VSAV(IMT,KM)
      REAL :: RHON(IMT,KM)
      REAL :: RHOS(IMT,KM)
      REAL :: rhos_adj(IMT,KM)
      REAL :: FUWTP(IMTP1,KM)
      REAL :: FUW(IMTP1,KM)
      REAL :: FUWT(IMTP1,KM)
      REAL :: FVNTP(IMT,KM)
      REAL :: FVN(IMT,KM)
      REAL :: FVNT(IMT,KM)
      REAL :: FVSU(IMT,KM)
      REAL :: FVSTP(IMT,KM)
      REAL :: FVST(IMT,KM)
      REAL :: FLUXST(IMT,KM,NT)
      REAL :: FLUXNT(IMT,KM,NT)
      REAL :: FMM(IMT,KM)
      REAL :: FM(IMT,KM)
      REAL :: FMP(IMT,KM)
      REAL :: GM(IMT,KM)
      REAL :: UCLINP(IMT_BIH,KM_BIH)
      REAL :: VCLINP(IMT_BIH,KM_BIH)
      REAL :: D2U(IMT_BIH,KM_BIH,3)
      REAL :: D2V(IMT_BIH,KM_BIH,3)
      REAL :: FMPP(IMT_BIH,KM_BIH)
      REAL :: UOVER(IMT)
      REAL :: UDIF (IMT,KM)
      REAL :: UUNDER(IMT)
      REAL :: VOVER(IMT)
      REAL :: VDIF (IMT,KM)
      REAL :: VUNDER(IMT)
      REAL :: WTP(IMT,KMP1)
      REAL :: W(IMT,KMP1)
      REAL :: WT(IMT,KMP1)
      REAL :: TDIF(IMT,KMP2,NTMIN2)
      REAL :: DXTQ  (IMT,KM)
      REAL :: DXUQ  (IMT,KM)
      REAL :: DXT4RQ(IMT,KM)
      REAL :: DXU2RQ(IMT,KM)
      REAL :: DZ2RQ (IMT,KM)
      REAL :: DZZQ  (IMT,KM)
      REAL :: DZZ2RQ(IMT,KM)
      REAL :: C2DZQ (IMT,KM)
      REAL :: EEHQ  (IMT,KM)
      REAL :: EEMQ  (IMT,KM)
      REAL :: FFHQ  (IMT,KM)
      REAL :: FFMQ  (IMT,KM)
      REAL :: D2T(IMT_BIH,KM_BIH_TOP,NT,3)
