! ROCACDG; for ocean assimilation; documented in CODACDG
      INTEGER :: NO_CAT_MAX
      INTEGER :: NO_OP_DG
      INTEGER :: MAX_OBS_DG
      INTEGER :: MAX_SEL_DG
      INTEGER :: MAX_PRM_DG
      INTEGER :: MAX_LEV_DG
      INTEGER :: I_TIM_STP_DG
      INTEGER :: LEV_DG(MAX_LEV_DG)
      INTEGER :: I_UNT_DG
      INTEGER :: NO_PRT_DG
      INTEGER :: NO_OBS_DG1
      INTEGER :: ID_OBS_DG1(MAX_OBS_DG)
      INTEGER :: NO_SEL_DG1
      INTEGER :: I_PO_SEL_DG1(MAX_SEL_DG)
      INTEGER :: NO_ACC_DG1
      INTEGER :: MOD_DG1
      INTEGER :: JOB_ACC_DG1
      INTEGER :: NE_GRD_DG1
      INTEGER :: I_CAT_DG2(NO_CAT_MAX)
      INTEGER :: I_SUB_DG2
      INTEGER :: I_COL_DG5
      INTEGER :: I_ROW_DG5
      INTEGER :: NE_AG_PT_DG5
      INTEGER :: MAX_ACC_DG5
      INTEGER :: JOB_ACC_DG5
      INTEGER :: NE_GRD_DG5

      LOGICAL :: LL_MST_DG
      LOGICAL :: LL_AC_DG
      LOGICAL :: LL_OP_DG(NO_OP_DG)
      LOGICAL :: LL_51_DG
      LOGICAL :: LL_SEL_DG
      LOGICAL :: LL_CAT_DG(NO_CAT_MAX)
      LOGICAL :: LL_TIT_DG1
      LOGICAL :: LL_JOB_DG1
      LOGICAL :: LL_BND_DG2
      LOGICAL :: LL_JOB_DG5

      REAL :: RLAT_N_DG1
      REAL :: RLAT_S_DG1
      REAL :: RLON_W_DG1
      REAL :: RLON_E_DG1
      REAL :: VAL_DG1(MAX_SEL_DG, MAX_PRM_DG)
      REAL :: RLAT_PT_DG5
      REAL :: RLON_PT_DG5

      CHARACTER(LEN=10) :: CC_DES_DG1(MAX_PRM_DG)
      CHARACTER(LEN=24) :: CC_TIT1_DG1
      CHARACTER(LEN=32) :: CC_TIT2_DG1
      CHARACTER(LEN=30) :: CC_TIT3_DG1
      CHARACTER(LEN=55) :: CC_TIT4_DG1
! ROCACDG end
