! ROCPMC; for ocean assimilation; documented in CODPMC
      REAL :: O_TIM_WIN_STR_CAT(NO_CAT_MAX)
      REAL :: O_TIM_WIN_FIN_CAT(NO_CAT_MAX)
      REAL :: O_FAC_STR_COR_CAT(NO_CAT_MAX)
      REAL :: O_FAC_MID_COR_CAT(NO_CAT_MAX)
      REAL :: O_FAC_FIN_COR_CAT(NO_CAT_MAX)
      REAL :: O_COF_NUD_CAT(NO_CAT_MAX)

      LOGICAL :: LLO_OMIT_OBS_CAT(NO_CAT_MAX)
      LOGICAL :: LLO_VRY_OBS_CAT(NO_CAT_MAX)
      LOGICAL :: LLO_EVO_POS_CAT(NO_CAT_MAX)
      LOGICAL :: LLO_EVO_VAL_CAT(NO_CAT_MAX)
      LOGICAL :: LLO_STAT_INC_CAT(NO_CAT_MAX)

      INTEGER :: JO_CAT_GRP(3,NO_TYP_MAX)
! ROCPMC end
